 
ME_Processing_Resource Me_Regular_Processor leon3 Proc_Res_Canvas 15 15 
ME_Timer Me_System_Timer leon3 Proc_Res_Canvas 225 33 
ME_Scheduler Me_Primary_Scheduler rtems Proc_Res_Canvas 213 101 
ME_Scheduler Me_Primary_Scheduler rtems Sched_Server_Canvas 388 91 
ME_Scheduling_Server Me_Server tmchannelctrl Sched_Server_Canvas 137 95 
ME_Scheduling_Server Me_Server epdmanager Sched_Server_Canvas 261 229 
ME_Scheduling_Server Me_Server hkfdirmng Sched_Server_Canvas 515 231 
ME_Scheduling_Server Me_Server bkgtcexec Sched_Server_Canvas 659 96 
ME_Shared_Resource Me_Priority_Inheritance_Resource systemdatapool Shared_Res_Canvas 15 15 
ME_Operation Me_Simple_Operation fgettc Operation_Canvas 15 15 
ME_Operation Me_Simple_Operation ftxtmlist Operation_Canvas 165 15 
ME_Operation Me_Simple_Operation fsendtmlist Operation_Canvas 315 15 
ME_Operation Me_Simple_Operation freplytmqueued Operation_Canvas 465 15 
ME_Operation Me_Composite_Operation fsendtmlist_replytmqueued Operation_Canvas 393 128 
ME_Operation Me_Simple_Operation fdohk_fdir Operation_Canvas 167 128 
ME_Transaction Me_Regular_Transaction transacceptedtc Transaction_Canvas 15 15 
ME_Transaction Me_Regular_Transaction transhk_fdir Transaction_Canvas 236 15 
ME_Link Me_External_Link ev_newtc,transacceptedtc transacceptedtc 33 26 
ME_Link Me_Internal_Link ev_tx_accepted,transacceptedtc transacceptedtc 35 158 
ME_Link Me_Internal_Link ev_tx_tmlist,transacceptedtc transacceptedtc 34 288 
ME_Link Me_Internal_Link dl_new_tc,transacceptedtc transacceptedtc 291 155 
ME_Link Me_External_Link ev_hk_fdir,transhk_fdir transhk_fdir 40 14 
ME_Link Me_Internal_Link dl_hk_fdir,transhk_fdir transhk_fdir 313 140 
ME_Link Me_Internal_Link ev_txtmlist,transhk_fdir transhk_fdir 40 137 
ME_Link Me_Internal_Link ev_sendtm_reply,transhk_fdir transhk_fdir 43 256 
ME_Event_Handler Me_Simple_Event_Handler 1,transacceptedtc transacceptedtc 13 78 
ME_Event_Handler Me_Simple_Event_Handler 2,transacceptedtc transacceptedtc 12 207 
ME_Event_Handler Me_Simple_Event_Handler 3,transacceptedtc transacceptedtc 268 78 
ME_Event_Handler Me_Simple_Event_Handler 1,transhk_fdir transhk_fdir 18 61 
ME_Event_Handler Me_Simple_Event_Handler 2,transhk_fdir transhk_fdir 18 182 
ME_Event_Handler Me_Simple_Event_Handler 3,transhk_fdir transhk_fdir 292 61 
